icons_format = "{icon}"

[theme]
theme = "gruvbox-dark"
[theme.overrides]
idle_bg = "#504945"
idle_fg = "#ebdbb2"

[icons]
icons = "awesome"
#[icons.overrides]
#bat = " | | "
#bat_full = " |X| "
#bat_charging = " |^| "
#bat_discharging = " |v| "

[[block]]
block = "cpu"

[[block]]
block = "temperature"
format = " $icon $average"
interval = 10
chip = "*-pci-*"

[[block]]
block = "disk_space"
info_type = "used"
alert = 90.0
warning = 80.0
format = " $icon $percentage "

[[block]]
block = "memory"
display_type = "memory"
format_mem = " $icon $mem_used_percents.eng(1) "
format_swap = " $icon $swap_used_percents.eng(1) "

[[block]]
block = "battery"
interval = 10
info = 60
good = 60
warning = 50
critical = 15
format = " $icon  $percentage "

[[block]]
block = "sound"
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "net"
device = "^wl*"
format = " $icon {$ip $signal_strength $speed_down}"
interval = 5

[[block]]
block = "time"
interval = 5
format = " %a %m/%d %R "
